- hosts: all
  become: yes
  remote_user: test1

  tasks:
    - name: Install htop 
      become: true
      become_method: sudo
      apt:
        name: htop 
        state: present

    - name: Setup allow password authentication sshd
      become: true
      become_method: sudo
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PasswordAuthentication'
        line="PasswordAuthentication yes"
        state=present 
        backup=yes
      notify:
        - restart sshd

  handlers:
    - name: restart sshd
      service:
          name: sshd
          state: restarted
